Messages:
  Start: "Some start"
  NotAuthorized: "You are not authorized! Type /start command to authorize"
  AuthSuccess: "Successfully authorized!"

  CategoryExists: "The category *%s* already exists!"
  CategoryNotFound: "The category *%s* was not found!"
  CategoryCreated: "Category *%s* was created successfully!"
  CategoryRemoved: "Category *%s* was successfully removed!"
  CategoryRenamed: "Category *%s* was successfully renamed to *%s*"
  RenameCategoryWrongSyntax: "Please use the given syntax: /renamecategory _oldName newName_"
  SelectCategories: "Select categories that you want to remove"
  ListCategories: "Here is your categories:"

  SelectCategoryForNote: "Select in which category you want to put this note"
  SelectCategoryToRemoveNotes: "Select in which category you want to remove notes"
  SelectCategoryToListNotes: "Select in which category you want to list notes"
  NoteCreated: "Note was added successfully!"
  NoteRemoved: "Note was removed successfully!"
  SelectNotes: "Select notes to remove"
  ListNotes: "Here is all your notes"
  ListNotesInCategory: "Here is your notes in category *%s*:"
  NoNotesInCategory: "There is no notes in category *%s*..."
